import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";

import LayoutProvider from "@/providers/LayoutProvider";
import AuthProvider from "@/providers/AuthProvider";
import QueryProvider from "@/providers/QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GALLERIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-screen h-screen overflow-x-hidden flex flex-col relative pt-20 selection:text-white selection:bg-purple-500`}
        suppressHydrationWarning
      >
        <QueryProvider>
          <AuthProvider>
            <LayoutProvider>{children}</LayoutProvider>
          </AuthProvider>
        </QueryProvider>

        <Toaster />

        {/* {children} */}
      </body>
    </html>
  );
}
