import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";

import LayoutProvider from "@/providers/LayoutProvider";
import AuthProvider from "@/providers/AuthProvider";
import QueryProvider from "@/providers/QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GALLERIO",
  applicationName: "GALLERIO",
  description: "Generated by create next app",
  authors: [{ name: "Half-blood prince" }, { name: "Nyo Min Khat" }],
  creator: "Half-blood prince",
  keywords: [
    "Gallery",
    "Save Photos",
    "Photos",
    "Images",
    "NextJs",
    "ReactJs",
    "Cloudinary",
  ],
  openGraph: {
    images: "https://portfolio-nmk.vercel.app/project-imgs/gallerio.webp",
    type: "website",
    url: "https://gallerio-gamma.vercel.app/",
    title: "GALLERIO",
    description: "Generated by create next app",
  },
  twitter: {
    card: "summary_large_image",
    title: "GALLERIO",
    description: "Generated by create next app",
    creator: "Nyo Min Khat",
    images: {
      url: "https://portfolio-nmk.vercel.app/project-imgs/gallerio.webp",
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} w-screen h-screen overflow-x-hidden flex flex-col relative pt-20 selection:text-white selection:bg-purple-500`}
        suppressHydrationWarning
      >
        <QueryProvider>
          <AuthProvider>
            <LayoutProvider>{children}</LayoutProvider>
          </AuthProvider>
        </QueryProvider>

        <Toaster />

        {/* {children} */}
      </body>
    </html>
  );
}
