import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";

import LayoutProvider from "@/providers/LayoutProvider";
import AuthProvider from "@/providers/AuthProvider";
import QueryProvider from "@/providers/QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GALLERIO",
  applicationName: "GALLERIO",
  description: "Generated by create next app",
  authors: [{ name: "Half-blood prince" }, { name: "Nyo Min Khat" }],
  creator: "Half-blood prince",
  keywords: [
    "Gallery",
    "Save Photos",
    "Photos",
    "Images",
    "NextJs",
    "ReactJs",
    "Cloudinary",
  ],
  openGraph: {
    images: "https://metatags.io/images/meta-tags.png",
    type: "website",
    url: "https://gallerio-gamma.vercel.app/",
    title: "GALLERIO",
    description: "Generated by create next app",
  },
  twitter: {
    card: "summary_large_image",
    title: "GALLERIO",
    description: "Generated by create next app",
    creator: "Nyo Min Khat",
    images: {
      url: "https://metatags.io/images/meta-tags.png",
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      {/* <!-- Primary Meta Tags -->
<title>GALLERIO</title>
<meta name="title" content="GALLERIO" />
<meta name="description" content="Generated by create next app" />

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website" />
<meta property="og:url" content="https://gallerio-gamma.vercel.app/" />
<meta property="og:title" content="GALLERIO" />
<meta property="og:description" content="Generated by create next app" />
<meta property="og:image" content="https://metatags.io/images/meta-tags.png" />

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image" />
<meta property="twitter:url" content="https://gallerio-gamma.vercel.app/" />
<meta property="twitter:title" content="GALLERIO" />
<meta property="twitter:description" content="Generated by create next app" />
<meta property="twitter:image" content="https://metatags.io/images/meta-tags.png" />

<!-- Meta Tags Generated with https://metatags.io --> */}
      <body
        className={`${inter.className} w-screen h-screen overflow-x-hidden flex flex-col relative pt-20 selection:text-white selection:bg-purple-500`}
        suppressHydrationWarning
      >
        <QueryProvider>
          <AuthProvider>
            <LayoutProvider>{children}</LayoutProvider>
          </AuthProvider>
        </QueryProvider>

        <Toaster />

        {/* {children} */}
      </body>
    </html>
  );
}
